id: IF54DDFE9
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:01:01.051417
last_modified: 2023-02-08 15:01:01.051553
source_metadata:
  title: 'BA: Daśabhūmikasūtra'
  language: zh
bases:
  '4449':
    base_file: 4449.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
